require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MailingListsController do

  # This should return the minimal set of attributes required to create a valid
  # MailingList. As you add validations to MailingList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MailingListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mailing_lists as @mailing_lists" do
      mailing_list = MailingList.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mailing_lists).should eq([mailing_list])
    end
  end

  describe "GET show" do
    it "assigns the requested mailing_list as @mailing_list" do
      mailing_list = MailingList.create! valid_attributes
      get :show, {:id => mailing_list.to_param}, valid_session
      assigns(:mailing_list).should eq(mailing_list)
    end
  end

  describe "GET new" do
    it "assigns a new mailing_list as @mailing_list" do
      get :new, {}, valid_session
      assigns(:mailing_list).should be_a_new(MailingList)
    end
  end

  describe "GET edit" do
    it "assigns the requested mailing_list as @mailing_list" do
      mailing_list = MailingList.create! valid_attributes
      get :edit, {:id => mailing_list.to_param}, valid_session
      assigns(:mailing_list).should eq(mailing_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MailingList" do
        expect {
          post :create, {:mailing_list => valid_attributes}, valid_session
        }.to change(MailingList, :count).by(1)
      end

      it "assigns a newly created mailing_list as @mailing_list" do
        post :create, {:mailing_list => valid_attributes}, valid_session
        assigns(:mailing_list).should be_a(MailingList)
        assigns(:mailing_list).should be_persisted
      end

      it "redirects to the created mailing_list" do
        post :create, {:mailing_list => valid_attributes}, valid_session
        response.should redirect_to(MailingList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mailing_list as @mailing_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        MailingList.any_instance.stub(:save).and_return(false)
        post :create, {:mailing_list => {  }}, valid_session
        assigns(:mailing_list).should be_a_new(MailingList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MailingList.any_instance.stub(:save).and_return(false)
        post :create, {:mailing_list => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mailing_list" do
        mailing_list = MailingList.create! valid_attributes
        # Assuming there are no other mailing_lists in the database, this
        # specifies that the MailingList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MailingList.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => mailing_list.to_param, :mailing_list => { "these" => "params" }}, valid_session
      end

      it "assigns the requested mailing_list as @mailing_list" do
        mailing_list = MailingList.create! valid_attributes
        put :update, {:id => mailing_list.to_param, :mailing_list => valid_attributes}, valid_session
        assigns(:mailing_list).should eq(mailing_list)
      end

      it "redirects to the mailing_list" do
        mailing_list = MailingList.create! valid_attributes
        put :update, {:id => mailing_list.to_param, :mailing_list => valid_attributes}, valid_session
        response.should redirect_to(mailing_list)
      end
    end

    describe "with invalid params" do
      it "assigns the mailing_list as @mailing_list" do
        mailing_list = MailingList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MailingList.any_instance.stub(:save).and_return(false)
        put :update, {:id => mailing_list.to_param, :mailing_list => {  }}, valid_session
        assigns(:mailing_list).should eq(mailing_list)
      end

      it "re-renders the 'edit' template" do
        mailing_list = MailingList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MailingList.any_instance.stub(:save).and_return(false)
        put :update, {:id => mailing_list.to_param, :mailing_list => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mailing_list" do
      mailing_list = MailingList.create! valid_attributes
      expect {
        delete :destroy, {:id => mailing_list.to_param}, valid_session
      }.to change(MailingList, :count).by(-1)
    end

    it "redirects to the mailing_lists list" do
      mailing_list = MailingList.create! valid_attributes
      delete :destroy, {:id => mailing_list.to_param}, valid_session
      response.should redirect_to(mailing_lists_url)
    end
  end

end
